---
# defaults file for python

python_apt_packages:
  - sloccount
  - python-pip
  - python-virtualenv
  - git

python_pip_libraries:
  - pylint
  - clonedigger
  - nose
  - nosexcover
  - pyflakes
  - lxml
  - python-jenkins

jenkins_remote_host: localhost
jenkins_remote_port: 8080
jenkins_admin_username: admin
jenkins_admin_password: <<<<< >>>>>
